"""User and Uploads Table

Revision ID: c9acc9230e3f
Revises: 
Create Date: 2023-11-10 11:40:30.474961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9acc9230e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('uploads',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('ix_Something6_id', table_name='Something6')
    op.drop_table('Something6')
    op.drop_index('ix_Something5_id', table_name='Something5')
    op.drop_table('Something5')
    op.drop_index('ix_Something7_id', table_name='Something7')
    op.drop_table('Something7')
    op.drop_index('ix_Something2_id', table_name='Something2')
    op.drop_table('Something2')
    op.drop_index('ix_Something1_id', table_name='Something1')
    op.drop_table('Something1')
    op.drop_index('ix_Something_id', table_name='Something')
    op.drop_table('Something')
    op.drop_index('ix_Something4_id', table_name='Something4')
    op.drop_table('Something4')
    op.drop_index('ix_Something3_id', table_name='Something3')
    op.drop_table('Something3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Something3',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something3_id', 'Something3', ['id'], unique=False)
    op.create_table('Something4',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something4_id', 'Something4', ['id'], unique=False)
    op.create_table('Something',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something_id', 'Something', ['id'], unique=False)
    op.create_table('Something1',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something1_id', 'Something1', ['id'], unique=False)
    op.create_table('Something2',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something2_id', 'Something2', ['id'], unique=False)
    op.create_table('Something7',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something7_id', 'Something7', ['id'], unique=False)
    op.create_table('Something5',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something5_id', 'Something5', ['id'], unique=False)
    op.create_table('Something6',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Series_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Data_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Suppressed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UNITS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Magnitude', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Series_title_4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Series_title_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('ix_Something6_id', 'Something6', ['id'], unique=False)
    op.drop_table('uploads')
    op.drop_table('users')
    # ### end Alembic commands ###
